# Generated by Django 5.1.2 on 2024-10-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viridian_accesibility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='assets',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='assets',
            field=models.DecimalField(decimal_places=0, max_digits=78),
        ),
    ]
